version: '3'

services:
  react-app:
    build: .
    ports:
      - "9501:3000"
    volumes:
      - .:/opereation-app
      - node_modules_volume:/opereation-app/node_modules
    tty: true
volumes:
  node_modules_volume:
    name: react_node_modules
